### ISSUE TITLE
mix function doesn't iterate through all the operations for the thread

### ISSUE THREAD

**Issue by sgopalan98** [jonhoo/bustle#13]
https://github.com/jonhoo/bustle/blob/6ab391ff4f5accd236161f7c61f1f406d85c167e/src/lib.rs#L451

Since the division is floor here, the for loop doesn't run for all the "ops" operations. 

Ex: ops = 2048 and op_mix.len() = 100. This creates a slice of length = 2000 and 48 operations are left out. Should this be the case? 

I feel like there was an assumption that the division is ceil because there is a clause in the for loop that breaks the loop prematurely. 

https://github.com/jonhoo/bustle/blob/6ab391ff4f5accd236161f7c61f1f406d85c167e/src/lib.rs#L455

**Comment by jonhoo** [comment]
Ah, yes, that does seem like just a straight-up error! I'm surprised it made it in though as this was a pretty straight port of the original C code :thinking: Makes me wonder whether the C version has the same bug. Would be happy to take a PR!

**Comment by sgopalan98** [comment]
Got it :) , I have created [a PR](https://github.com/jonhoo/bustle/pull/14) to fix this. Can you check if this is fine?

**Comment by Lol3rrr** [comment]
Is this still relevant/open as it seems resolved?

**Comment by jonhoo** [comment]
Ah, no, this was fixed in #14 — thanks!
